// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmtxviujpnmxjyvtjvsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtdHh2aXVqcG5teGp5dnRqdnNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjUxODAsImV4cCI6MjA2MTU0MTE4MH0.dMex8HR7JpyoGB0B0oiJ3MIZ6qNU4t78pCIrxVe9uJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // Desativa o armazenamento automático da sessão em localStorage
      persistSession: false,
    },
  }
);